function createfigure1(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Jan-2011 16:52:47

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.142011834319527 0.765251396648045 0.782988165680474],...
    'FontWeight','bold',...
    'FontSize',12);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.3 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerFaceColor',[0 0 0],...
    'Color',[0 0 0]);
set(plot1(1),'Marker','square','LineWidth',2,...
    'DisplayName','Curvature at Pole');
set(plot1(2),'Marker','o','LineWidth',1.25,'LineStyle','--',...
    'DisplayName','Minor Axis');

% Create xlabel
xlabel({'Aspect Ratio of','Minor to Major Axis'},'FontWeight','bold',...
    'FontSize',12);

% Create ylabel
ylabel({'Percent Change','from Baseline'},'FontWeight','bold','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.554846368715085 0.64283777120316 0.247905027932961 0.0899901380670611]);

