function createfigure2(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,X4,Y4,X5,Y5,X6,Y6,X7,Y7,X8,Y8,X9,Y9,X10,Y10,X11,Y11,X12,Y12,X13,Y13,X14,Y14,X15,Y15)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  X9:  vector of x data
%  Y9:  vector of y data
%  X10:  vector of x data
%  Y10:  vector of y data
%  X11:  vector of x data
%  Y11:  vector of y data
%  X12:  vector of x data
%  Y12:  vector of y data
%  X13:  vector of x data
%  Y13:  vector of y data
%  X14:  vector of x data
%  Y14:  vector of y data
%  X15:  vector of x data
%  Y15:  vector of y data

%  Auto-generated by MATLAB on 02-Jan-2011 19:06:57

% Create figure
figure1 = figure('Color',...
    [0.800000011920929 0.800000011920929 0.800000011920929]);

% polar currently does not support code generation, enter 'doc polar' for correct input syntax

% polar(...);

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create xlabel
xlabel({'Major Axis'},'FontWeight','bold','FontSize',12);

% Create ylabel
ylabel({'Minor Axis'},'FontWeight','bold','FontSize',12);

% Create plot
plot(X2,Y2,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X3,Y3,'LineWidth',1);

% Create plot
plot(X4,Y4,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X5,Y5,'LineWidth',1);

% Create plot
plot(X6,Y6,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X7,Y7,'LineWidth',1);

% Create plot
plot(X8,Y8,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X9,Y9,'LineWidth',1);

% Create plot
plot(X10,Y10,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X11,Y11,'LineWidth',1);

% Create plot
plot(X12,Y12,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X13,Y13,'LineWidth',1);

% Create plot
plot(X14,Y14,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X15,Y15,'LineWidth',1);

% Create line
annotation(figure1,'line',[0.266759776536313 0.258379888268156],...
    [0.580854043392505 0.581854043392505]);

% Create line
annotation(figure1,'line',[0.431564245810056 0.431564245810056],...
    [0.108481262327416 0.100591715976331]);

% Create line
annotation(figure1,'line',[0.599162011173184 0.599162011173184],...
    [0.100591715976331 0.110453648915187]);

% Create textbox
annotation(figure1,'textbox',...
    [0.579659217877096 0.0766469428007893 0.0325195530726257 0.0315581854043393],...
    'String',{'10'},...
    'FontWeight','bold',...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.418597765363129 0.0749506903353058 0.0325195530726257 0.0315581854043393],...
    'String',{'5'},...
    'FontWeight','bold',...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create line
annotation(figure1,'line',[0.26536312849162 0.255586592178771],...
    [0.346140039447732 0.347140039447732]);

% Create line
annotation(figure1,'line',[0.312849162011174 0.337988826815643],...
    [0.672583826429982 0.674556213017751],'LineWidth',1,'Color',[1 0 0]);

% Create line
annotation(figure1,'line',[0.312849162011174 0.339385474860337],...
    [0.639053254437871 0.639053254437873],'LineWidth',1,'Color',[0 0 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.293296089385478 0.617357001972392 0.220670391061452 0.0828402366864048],...
    'String',{'        Baseline Ellipse','        New Curve'},...
    'FontWeight','bold',...
    'FontSize',12,...
    'FitBoxToText','off');

